# Generated by Django 5.1.15 on 2026-09-03 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('logo_url', models.URLField(blank=True)),
                ('season', models.IntegerField(help_text='Current season year, e.g. 2026')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('short_name', models.CharField(blank=True, max_length=32)),
                ('logo_url', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('elo', models.FloatField(default=1500.0)),
                ('attack_strength', models.FloatField(default=1.0)),
                ('defence_strength', models.FloatField(default=1.0)),
                ('ratings_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_id', models.BigIntegerField(unique=True)),
                ('kickoff', models.DateTimeField(db_index=True)),
                ('round', models.CharField(blank=True, max_length=64)),
                ('venue', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=16)),
                ('home_goals', models.IntegerField(blank=True, null=True)),
                ('away_goals', models.IntegerField(blank=True, null=True)),
                ('home_goals_ht', models.IntegerField(blank=True, null=True)),
                ('away_goals_ht', models.IntegerField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='fixtures.league')),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='fixtures.team')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='fixtures.team')),
            ],
            options={
                'ordering': ['kickoff'],
            },
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_name', models.CharField(max_length=128)),
                ('reason', models.CharField(blank=True, max_length=128)),
                ('type', models.CharField(blank=True, help_text='missing | questionable', max_length=32)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='fixtures.fixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='fixtures.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookmaker', models.CharField(max_length=64)),
                ('market', models.CharField(help_text='1x2 | ou_2_5 | btts | dc', max_length=32)),
                ('selection', models.CharField(help_text='home | draw | away | over | ...', max_length=32)),
                ('price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='fixtures.fixture')),
            ],
            options={
                'indexes': [models.Index(fields=['fixture', 'market'], name='fixtures_od_fixture_1842db_idx')],
                'constraints': [models.UniqueConstraint(fields=('fixture', 'bookmaker', 'market', 'selection'), name='uniq_odds_per_book_selection')],
            },
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['kickoff', 'status'], name='fixtures_fi_kickoff_591c8e_idx'),
        ),
    ]
