# Generated by Django 5.1.15 on 2026-09-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='elo_applied',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
