# Generated by Django 5.1.15 on 2026-09-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_fixture_elo_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='away_attack_strength',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='team',
            name='away_defence_strength',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='team',
            name='home_attack_strength',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='team',
            name='home_defence_strength',
            field=models.FloatField(default=1.0),
        ),
    ]
