# Generated by Django 5.1.15 on 2026-09-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0003_team_away_attack_strength_team_away_defence_strength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='raw',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
