# Generated by Django 5.1.15 on 2026-09-08 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivingWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text="Shown to the user, e.g. 'USDT (TRC-20)'", max_length=64)),
                ('currency', models.CharField(help_text='usdt, btc …', max_length=16)),
                ('network', models.CharField(blank=True, help_text='TRC20, ERC20, BTC …', max_length=32)),
                ('address', models.CharField(max_length=128)),
                ('explorer_url', models.URLField(blank=True, help_text='Base URL for a transaction, e.g. https://tronscan.org/#/transaction/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='review_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reviewed_by',
            field=models.BigIntegerField(blank=True, help_text='Telegram id of the admin who decided.', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='tx_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Transaction hash as submitted by the user.', max_length=128),
        ),
        migrations.AddField(
            model_name='payment',
            name='wallet_address',
            field=models.CharField(blank=True, help_text='The address the user was shown.', max_length=128),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirming', 'Confirming'), ('review', 'Awaiting review'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('partial', 'Partially paid'), ('failed', 'Failed'), ('expired', 'Expired'), ('refunded', 'Refunded')], default='pending', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('tx_hash__gt', '')), fields=('tx_hash',), name='uniq_payment_tx_hash'),
        ),
    ]
